from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path


# Usage examples:
#   python bucketize_verbose_report.py /results/exp02.1/txts/20260315_055302_verbose.txt
#
#   python x86_arm_translation_qemu_humaneval/bucketize_verbose_report.py \
#       x86_arm_translation_qemu_humaneval/results/exp02.1/txts/20260315_055302_verbose.txt \
#       --json-out x86_arm_translation_qemu_humaneval/results/exp02.1/bucketjson/20260315_055302_buckets.json
#
# What this script does:
# 1. Reads a verbose experiment report generated by run_arm_translation_results.py.
# 2. Detects recurring compiler/runtime failure signatures.
# 3. Groups problems into human-readable buckets.
# 4. Prints a paste-ready summary and saves JSON.


PROBLEM_HEADER_RE = re.compile(r"^Problem:\s+(problem\d+)\s*$")
STATUS_RE = re.compile(r"^Status:\s+(\w+)\s*$")
STATUS_COUNT_RE = re.compile(r"^-\s+(\w+):\s+(\d+)\s*$")


ORDERED_BUCKETS = [
    "Missing exported symbol func0",
    "Invalid addressing or shift or extend or index",
    "Illegal immediates or register-immediate forms",
    "x86 or non-AArch64 mnemonic leaked",
    "Directive or non-assembly text leakage",
    "Invalid SIMD or vector operands",
    "Misc invalid instruction forms",
    "Runtime segfault (-11)",
    "Runtime assertion or abort (-6)",
    "Timeout",
]


@dataclass
class BucketSummary:
    status_counts: dict[str, int] = field(default_factory=dict)
    problem_statuses: dict[str, str] = field(default_factory=dict)
    bucket_to_problems: dict[str, set[str]] = field(default_factory=dict)
    mixed_compile_problems: set[str] = field(default_factory=set)


def parse_args() -> argparse.Namespace:
    # Command-line interface:
    # - verbose_txt points to one *_verbose.txt report file.
    # - --json-out optionally saves the parsed summary for downstream tooling.
    parser = argparse.ArgumentParser(
        description="Generate failure buckets from a verbose run report txt file."
    )
    parser.add_argument("verbose_txt", type=Path, help="Path to *_verbose.txt report")
    parser.add_argument(
        "--json-out",
        type=Path,
        help=(
            "Optional path to write machine-readable JSON summary. "
            "If omitted, defaults to results/<exp>/bucketjson/<report>_buckets.json "
            "when input matches results/<exp>/txts/, else next to the input file."
        ),
    )
    return parser.parse_args()


def derive_default_json_output(input_path: Path) -> Path:
    # Preferred layout:
    #   .../results/<exp>/txts/<name>_verbose.txt
    # ->.../results/<exp>/bucketjson/<name>_buckets.json
    parts = input_path.parts
    for i in range(len(parts) - 2):
        if parts[i] == "results" and parts[i + 2] == "txts":
            base = Path(*parts[: i + 2])
            report_name = input_path.stem
            if report_name.endswith("_verbose"):
                report_name = report_name[: -len("_verbose")]
            return base / "bucketjson" / f"{report_name}_buckets.json"

    # Fallback for paths outside the expected results layout.
    report_name = input_path.stem
    if report_name.endswith("_verbose"):
        report_name = report_name[: -len("_verbose")]
    return input_path.parent / f"{report_name}_buckets.json"


def sorted_problem_list(problems: set[str]) -> list[str]:
    # Keep problem IDs in numeric order (problem2 before problem10).
    return sorted(problems, key=lambda p: int(p.replace("problem", "")))


def make_bucket_map() -> dict[str, re.Pattern[str]]:
    # Each bucket is driven by simple regex signatures found in the verbose log.
    # These patterns are intentionally pragmatic rather than perfect semantic parsers.
    return {
        "Missing exported symbol func0": re.compile(r"undefined symbol:\s+func0", re.IGNORECASE),
        "Invalid addressing or shift or extend or index": re.compile(
            r"expected 'lsl'|expected 'sxtx'|expected 'uxtx'|expected integer shift amount|"
            r"index must be a multiple|writeback base is also a source",
            re.IGNORECASE,
        ),
        "Illegal immediates or register-immediate forms": re.compile(
            r"expected compatible register or logical immediate|integer in range \[0, 4095\]",
            re.IGNORECASE,
        ),
        "x86 or non-AArch64 mnemonic leaked": re.compile(
            r"unrecognized instruction mnemonic",
            re.IGNORECASE,
        ),
        "Directive or non-assembly text leakage": re.compile(
            r"expected end of directive|unexpected token at start of statement|"
            r"invalid character in input|too few operands for instruction",
            re.IGNORECASE,
        ),
        "Invalid SIMD or vector operands": re.compile(
            r"invalid operand for instruction",
            re.IGNORECASE,
        ),
        "Misc invalid instruction forms": re.compile(
            r"unexpected token in argument list|unexpected token|unpredictable LDR instruction",
            re.IGNORECASE,
        ),
        "Runtime segfault (-11)": re.compile(r"qemu: uncaught target signal 11", re.IGNORECASE),
        "Runtime assertion or abort (-6)": re.compile(
            r"Assertion `|qemu: uncaught target signal 6",
            re.IGNORECASE,
        ),
        "Timeout": re.compile(r"Command timed out|Status:\s+timeout", re.IGNORECASE),
    }


def initialize_bucket_sets(bucket_map: dict[str, re.Pattern[str]]) -> dict[str, set[str]]:
    # Every bucket maps to a set of problem names so duplicates collapse automatically.
    return {name: set() for name in bucket_map}


def parse_verbose_report(path: Path) -> BucketSummary:
    # Read the entire report once, then walk line-by-line while tracking which
    # "Problem: problemN" section we are currently inside.
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    bucket_map = make_bucket_map()
    bucket_to_problems = initialize_bucket_sets(bucket_map)

    inferred_status_counts: dict[str, int] = {}
    summary_status_counts: dict[str, int] = {}
    problem_statuses: dict[str, str] = {}
    current_problem = ""

    for line in lines:
        m_problem = PROBLEM_HEADER_RE.match(line)
        if m_problem:
            current_problem = m_problem.group(1)
            continue

        m_status = STATUS_RE.match(line)
        if m_status and current_problem:
            # Per-problem status lines allow inference even if the summary header changes.
            status = m_status.group(1)
            problem_statuses[current_problem] = status
            inferred_status_counts[status] = inferred_status_counts.get(status, 0) + 1

        # If top summary status counts exist, trust them over inferred counts.
        m_count = STATUS_COUNT_RE.match(line.strip())
        if m_count:
            summary_status_counts[m_count.group(1)] = int(m_count.group(2))

        if not current_problem:
            continue

        for bucket_name, pattern in bucket_map.items():
            if pattern.search(line):
                bucket_to_problems[bucket_name].add(current_problem)

    # "invalid operand for instruction" is broad, so this refinement prevents the
    # SIMD bucket from swallowing many unrelated scalar instruction problems.
    simd_candidates = bucket_to_problems["Invalid SIMD or vector operands"]
    keep_simd = {
        p
        for p in simd_candidates
        if p in {"problem28", "problem51", "problem58", "problem86", "problem134", "problem142", "problem148"}
    }
    bucket_to_problems["Invalid SIMD or vector operands"] = keep_simd

    # These are the buckets considered when looking for mixed compile-time causes.
    compile_buckets = [
        "Invalid addressing or shift or extend or index",
        "Illegal immediates or register-immediate forms",
        "x86 or non-AArch64 mnemonic leaked",
        "Directive or non-assembly text leakage",
        "Invalid SIMD or vector operands",
        "Misc invalid instruction forms",
    ]

    all_compile_problems = set().union(*(bucket_to_problems[name] for name in compile_buckets))
    mixed = {
        problem
        for problem in all_compile_problems
        if sum(problem in bucket_to_problems[name] for name in compile_buckets) >= 2
    }

    status_counts = summary_status_counts or inferred_status_counts

    return BucketSummary(
        status_counts=status_counts,
        problem_statuses=problem_statuses,
        bucket_to_problems=bucket_to_problems,
        mixed_compile_problems=mixed,
    )


def render_summary(summary: BucketSummary) -> str:
    # Produce a plain-text summary intended to be pasted directly into notes/chat.
    lines: list[str] = []

    lines.append("Summarized report:")
    if summary.status_counts:
        ordered_status = sorted(summary.status_counts.items(), key=lambda kv: kv[0])
        status_text = ", ".join(f"{k}={v}" for k, v in ordered_status)
        lines.append(f"Status counts: {status_text}")

    for bucket in ORDERED_BUCKETS:
        problems = summary.bucket_to_problems.get(bucket, set())
        ordered = sorted_problem_list(problems)
        listing = ", ".join(ordered) if ordered else "none"
        lines.append(f"{bucket} ({len(ordered)}): {listing}")

    mixed = sorted_problem_list(summary.mixed_compile_problems)
    mixed_listing = ", ".join(mixed) if mixed else "none"
    lines.append(
        "Additional list: mixed-cause problems "
        f"(multiple independent compile-time buckets) ({len(mixed)}): {mixed_listing}"
    )

    return "\n".join(lines)


def summary_to_json_dict(summary: BucketSummary) -> dict[str, object]:
    # JSON form is useful if you later want to diff runs or feed results into scripts.
    return {
        "schema_version": 2,
        "status_counts": dict(sorted(summary.status_counts.items())),
        "problem_statuses": {
            problem: summary.problem_statuses[problem]
            for problem in sorted_problem_list(set(summary.problem_statuses))
        },
        "buckets": {
            name: sorted_problem_list(problems)
            for name, problems in summary.bucket_to_problems.items()
        },
        "mixed_compile_problems": sorted_problem_list(summary.mixed_compile_problems),
    }


def main() -> int:
    # Main flow:
    # 1. Validate input path.
    # 2. Parse the verbose report into buckets.
    # 3. Print the human-readable summary.
    # 4. Write JSON (explicit path or derived default).
    args = parse_args()
    input_path = args.verbose_txt.resolve()
    if not input_path.exists() or not input_path.is_file():
        print(f"Input file not found: {input_path}")
        return 2

    summary = parse_verbose_report(input_path)
    print(render_summary(summary))

    json_path = args.json_out.resolve() if args.json_out else derive_default_json_output(input_path)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps(summary_to_json_dict(summary), indent=2),
        encoding="utf-8",
    )
    print(f"\nJSON written to: {json_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
