"""
Gemini composer for repairing translated assembly that failed validation.

Purpose:
- Read errored problems from an experiment JSON generated by run_arm_translation_error_json.py.
- Build prompts for only errored problems.
- Run model calls asynchronously with retries.
- Re-run validation on fixed outputs.
- Emit brief and verbose run reports.

Prompt configurations (8):
- base
- error_only
- cfg_only
- dfg_only
- error_cfg
- error_dfg
- cfg_dfg
- error_cfg_dfg

Model options:
- gemini-3-flash-preview
- gemini-3.1-pro-preview

Example run command:
python GeminiComposer.py ../results/exp01.1 --source-language arm --model gemini-3-flash-preview --prompt-config error_only

How to run:
1) Ensure an error JSON exists in <input_dir>/jsons/ (generated by run_arm_translation_error_json.py),
     or pass one explicitly with --error-json.
2) Run from ComposerScripts or provide full paths.
3) Required positional argument:
     - input_dir: experiment folder containing <source-language>_asm and jsons
         (example: ../results/exp01.1)

Accepted flags:
- --run-label <text>
    Optional label for output folder naming. Default: input_dir folder name.
- --source-language {arm,x86,riscv}
    Language/ISA of input assembly to repair. Default: arm.
- --cfg-language {arm,x86,riscv}
    Language used to locate CFG files under Compiledown_HumanEval_O2/<lang>/cfg. Default: x86.
- --dfg-language {arm,x86,riscv}
    Language used to locate DFG files under Compiledown_HumanEval_O2/<lang>/dfg. Default: x86.
- --model {gemini-3-flash-preview,gemini-3.1-pro-preview}
    Gemini model name. Default: gemini-3-flash-preview.
- --prompt-config {base,error_only,cfg_only,dfg_only,error_cfg,error_dfg,cfg_dfg,error_cfg_dfg}
    Prompt composition strategy. Default: base.
- --error-json <path>
    Explicit *_error_problems.json path. Default: latest file in <input_dir>/jsons.
- --max-concurrency <int>
    Max parallel workers. Default comes from composer_config.py.
- --max-retries <int>
    Max attempts per problem. Default comes from composer_config.py.
- --retry-base-seconds <float>
    Exponential backoff base for retries. Default comes from composer_config.py.
- --clang <name>
    Clang executable used by validation reruns. Default: clang-17.
- --qemu <name>
    QEMU executable used by validation reruns. Default: qemu-aarch64.
- --sysroot <path>
    Optional sysroot passed to validation reruns.
- --timeout <seconds>
    Timeout per validation command. Default: 30.
- --no-link-math
    Passes through to validation reruns; disables -lm linking.

Additional examples:
- Use explicit error JSON:
    python GeminiComposer.py ../results/exp01.1 --error-json ../results/exp01.1/jsons/20260325_081256_error_problems.json --source-language arm
- Use custom run label and higher parallelism:
    python GeminiComposer.py ../results/exp01.1 --run-label exp01_1_patch --max-concurrency 16 --prompt-config error_cfg_dfg
- Use alternate model:
    python GeminiComposer.py ../results/exp01.1 --model gemini-3.1-pro-preview --prompt-config cfg_dfg

Default output location:
- Under ASMwork/x86arm_translation_qemu_humaneval/results/composer/
- Folder name: <run_label>_<model>_<promptconfig>_<timestamp>
    where run_label defaults to the input directory name (for example: exp01.1)

Intermediate artifacts for output-cleaning/debugging:
- prompts/<problem>_attempt<N>.txt: exact prompt sent to the model.
- raw_model_output/<problem>_attempt<N>.txt: verbatim model output.
- cleaned_model_output/<problem>_attempt<N>.txt: output after fence/prose stripping.
- clean_diagnostics/<problem>_attempt<N>.json: cleaning notes (removed sections, heuristics triggered).
- compile_probe/<problem>_attempt<N>.log: quick assembler parse/compile diagnostics before full rerun.

These extra artifacts make it easier to diagnose English prose leakage and improve cleaner rules safely.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import random
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from google import genai

from composer_config import (
    ALLOWED_MODELS,
    DEFAULT_CFG_LANGUAGE,
    DEFAULT_DFG_LANGUAGE,
    DEFAULT_SOURCE_LANGUAGE,
    DEFAULT_MAX_CONCURRENCY,
    DEFAULT_MAX_RETRIES,
    DEFAULT_MODEL,
    DEFAULT_RETRY_BASE_SECONDS,
    INPUT_TEST_DIR,
    PROMPT_CONFIGS,
    RUN_ERROR_JSON_SCRIPT,
    SUPPORTED_LANGUAGES,
    composer_brief_report_path,
    composer_fixed_asm_dir,
    composer_logs_dir,
    composer_original_error_asm_dir,
    composer_output_dir,
    composer_prompts_dir,
    composer_raw_output_dir,
    composer_verbose_report_path,
    language_cfg_dir,
    language_dfg_dir,
    benchmark_dir,
)


@dataclass(frozen=True)
class ComposerRuntimePaths:
    """All config-derived paths used by the composer runtime."""

    benchmark_arm_input_dir: Path
    input_experiment_dir: Path
    error_json_path: Path
    run_output_dir: Path
    prompts_dir: Path
    raw_output_dir: Path
    original_error_asm_dir: Path
    fixed_asm_dir: Path
    logs_dir: Path
    brief_report_path: Path
    verbose_report_path: Path
    cleaned_output_dir: Path
    clean_diagnostics_dir: Path
    compile_probe_dir: Path
    validation_json_dir: Path
    source_language: str
    cfg_language: str
    dfg_language: str
    cfg_dir: Path
    dfg_dir: Path


@dataclass
class ProblemSpec:
    name: str
    summary: str
    stderr: str
    source_asm_path: Path
    source_asm_name: str
    cfg_path: Path
    dfg_path: Path


@dataclass
class ProblemResult:
    name: str
    source_asm_path: Path
    fixed_asm_path: Path
    succeeded: bool
    attempts_used: int
    final_note: str
    attempts: list[dict[str, object]]


class QuotaExhaustedError(RuntimeError):
    """Raised when the API reports a hard daily quota exhaustion."""

    def __init__(self, problem_name: str, retry_delay_seconds: int | None, raw_error: str):
        self.problem_name = problem_name
        self.retry_delay_seconds = retry_delay_seconds
        self.raw_error = raw_error

        if retry_delay_seconds is None:
            message = (
                f"Daily model quota exhausted while processing {problem_name}. "
                "Stopping run now; retry after quota reset."
            )
        else:
            hours = retry_delay_seconds // 3600
            minutes = (retry_delay_seconds % 3600) // 60
            seconds = retry_delay_seconds % 60
            message = (
                f"Daily model quota exhausted while processing {problem_name}. "
                f"Stopping run now; retry in about {hours}h{minutes}m{seconds}s."
            )

        super().__init__(message)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Gemini composer (config-wired scaffold)")
    parser.add_argument(
        "input_dir",
        type=Path,
        help="Input experiment directory containing <language>_asm and jsons (for example: results/exp01.1)",
    )
    parser.add_argument(
        "--run-label",
        help="Optional label used in output naming; defaults to input_dir folder name",
    )
    parser.add_argument(
        "--source-language",
        default=DEFAULT_SOURCE_LANGUAGE,
        choices=SUPPORTED_LANGUAGES,
        help="Language/ISA of input assembly that composer repairs",
    )
    parser.add_argument(
        "--cfg-language",
        default=DEFAULT_CFG_LANGUAGE,
        choices=SUPPORTED_LANGUAGES,
        help="Language used to load CFG files",
    )
    parser.add_argument(
        "--dfg-language",
        default=DEFAULT_DFG_LANGUAGE,
        choices=SUPPORTED_LANGUAGES,
        help="Language used to load DFG files",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        choices=ALLOWED_MODELS,
        help="Gemini model name",
    )
    parser.add_argument(
        "--prompt-config",
        default="base",
        choices=PROMPT_CONFIGS,
        help="Prompt configuration strategy",
    )
    parser.add_argument(
        "--error-json",
        type=Path,
        help="Optional explicit path to *_error_problems.json; default uses latest for benchmark",
    )
    parser.add_argument("--max-concurrency", type=int, default=DEFAULT_MAX_CONCURRENCY)
    parser.add_argument("--max-retries", type=int, default=DEFAULT_MAX_RETRIES)
    parser.add_argument("--retry-base-seconds", type=float, default=DEFAULT_RETRY_BASE_SECONDS)
    parser.add_argument("--clang", default="clang-17", help="Clang executable for validation reruns")
    parser.add_argument("--qemu", default="qemu-aarch64", help="QEMU executable for validation reruns")
    parser.add_argument("--sysroot", type=Path, help="Optional sysroot for validation reruns")
    parser.add_argument("--timeout", type=int, default=30, help="Timeout for compile/qemu validation commands")
    parser.add_argument("--no-link-math", action="store_true", help="Pass --no-link-math to validation reruns")
    return parser.parse_args()


def resolve_runtime_paths(args: argparse.Namespace) -> ComposerRuntimePaths:
    input_experiment_dir = args.input_dir.resolve()
    if not input_experiment_dir.exists() or not input_experiment_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {input_experiment_dir}")

    benchmark_arm_input_dir = input_experiment_dir / f"{args.source_language}_asm"
    if not benchmark_arm_input_dir.exists() or not benchmark_arm_input_dir.is_dir():
        raise FileNotFoundError(
            f"Source asm directory does not exist: {benchmark_arm_input_dir}"
        )

    if args.error_json is not None:
        error_json_path = args.error_json.resolve()
    else:
        json_dir = input_experiment_dir / "jsons"
        candidates = []
        if json_dir.exists() and json_dir.is_dir():
            candidates = sorted(
                json_dir.glob("*_error_problems.json"),
                key=lambda p: p.stat().st_mtime,
            )
        if not candidates:
            raise FileNotFoundError(
                f"No *_error_problems.json found in {json_dir}. "
                "Run run_arm_translation_error_json.py first or pass --error-json."
            )
        error_json_path = candidates[-1].resolve()

    run_label = args.run_label or input_experiment_dir.name
    run_output_dir = composer_output_dir(
        benchmark_name=run_label,
        model_name=args.model,
        prompt_config=args.prompt_config,
    )

    return ComposerRuntimePaths(
        benchmark_arm_input_dir=benchmark_arm_input_dir,
        input_experiment_dir=input_experiment_dir,
        error_json_path=error_json_path,
        run_output_dir=run_output_dir,
        prompts_dir=composer_prompts_dir(run_output_dir),
        raw_output_dir=composer_raw_output_dir(run_output_dir),
        original_error_asm_dir=composer_original_error_asm_dir(run_output_dir, args.source_language),
        fixed_asm_dir=composer_fixed_asm_dir(run_output_dir, args.source_language),
        logs_dir=composer_logs_dir(run_output_dir),
        brief_report_path=composer_brief_report_path(run_output_dir),
        verbose_report_path=composer_verbose_report_path(run_output_dir),
        cleaned_output_dir=run_output_dir / "cleaned_model_output",
        clean_diagnostics_dir=run_output_dir / "clean_diagnostics",
        compile_probe_dir=run_output_dir / "compile_probe",
        validation_json_dir=run_output_dir / "validation_json",
        source_language=args.source_language,
        cfg_language=args.cfg_language,
        dfg_language=args.dfg_language,
        cfg_dir=language_cfg_dir(args.cfg_language),
        dfg_dir=language_dfg_dir(args.dfg_language),
    )


def _log(message: str) -> None:
    now = time.strftime("%H:%M:%S")
    print(f"[{now}] {message}")


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _append_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(content)


def _is_asm_like_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return True
    if stripped.startswith((".", "//", "/*", "*", "#")):
        return True
    if re.match(r"^[A-Za-z_.$][\w.$]*:\s*$", stripped):
        return True
    # Single-letter branch mnemonics (for example: b, b.eq) are valid ARM/AArch64 instructions.
    if re.match(r"^b(\.[A-Za-z0-9]+)?\b", stripped):
        return True
    if re.match(r"^[a-z]{2,8}(\.[A-Za-z0-9]+)?\b", stripped):
        return True
    return False


def clean_model_output(text: str) -> tuple[str, dict[str, object]]:
    """Strip common markdown/prose wrappers and return diagnostics."""

    raw = text or ""
    lines = raw.splitlines()
    without_fences = [line for line in lines if not line.strip().startswith("```")]

    first_idx = 0
    while first_idx < len(without_fences) and not _is_asm_like_line(without_fences[first_idx]):
        first_idx += 1

    last_idx = len(without_fences) - 1
    while last_idx >= first_idx and not _is_asm_like_line(without_fences[last_idx]):
        last_idx -= 1

    if first_idx <= last_idx:
        cleaned_lines = without_fences[first_idx : last_idx + 1]
    else:
        cleaned_lines = []

    cleaned = "\n".join(cleaned_lines).strip()
    diagnostics = {
        "raw_line_count": len(lines),
        "fence_lines_removed": len(lines) - len(without_fences),
        "leading_non_asm_lines_removed": first_idx,
        "trailing_non_asm_lines_removed": max(0, len(without_fences) - last_idx - 1) if without_fences else 0,
        "cleaned_line_count": len(cleaned_lines),
        "is_empty_after_clean": cleaned == "",
    }
    return cleaned, diagnostics


def _extract_retry_delay_seconds(error_text: str) -> int | None:
    match = re.search(r"retryDelay'\s*:\s*'(\d+)s'", error_text)
    if match:
        return int(match.group(1))
    return None


def _is_daily_quota_exhausted(error_text: str) -> bool:
    return (
        "RESOURCE_EXHAUSTED" in error_text
        and (
            "generate_requests_per_model_per_day" in error_text
            or "GenerateRequestsPerDayPerProjectPerModel" in error_text
        )
    )


def resolve_source_asm(benchmark_arm_input_dir: Path, problem_name: str) -> Path:
    matches = sorted(benchmark_arm_input_dir.glob(f"{problem_name}_*.s"))
    if not matches:
        raise FileNotFoundError(
            f"Could not find source ASM for {problem_name} in {benchmark_arm_input_dir}"
        )
    return matches[0]


def resolve_graph_path(graph_dir: Path, problem_name: str, graph_kind: str) -> Path | None:
    """Resolve CFG/DFG files across common naming variants.

    Supported examples include:
    - problem105_cfg.txt
    - problem105_O2_cfg.txt
    - problem105_dfg.txt
    - problem105_O2_dfg.s
    """

    normalized_kind = graph_kind.strip().lower()
    patterns = [
        f"{problem_name}_{normalized_kind}.txt",
        f"{problem_name}_{normalized_kind}.s",
        f"{problem_name}_*_{normalized_kind}.txt",
        f"{problem_name}_*_{normalized_kind}.s",
    ]

    for pattern in patterns:
        matches = sorted(graph_dir.glob(pattern))
        if matches:
            return matches[0]
    return None


def _is_readable_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        with path.open("r", encoding="utf-8"):
            return True
    except OSError:
        return False


def _is_readable_dir(path: Path) -> bool:
    if not path.exists() or not path.is_dir():
        return False
    try:
        next(path.iterdir(), None)
        return True
    except OSError:
        return False


def load_problem_specs(paths: ComposerRuntimePaths, args: argparse.Namespace) -> list[ProblemSpec]:
    issues: list[str] = []
    require_cfg = args.prompt_config in {"cfg_only", "error_cfg", "cfg_dfg", "error_cfg_dfg"}
    require_dfg = args.prompt_config in {"dfg_only", "error_dfg", "cfg_dfg", "error_cfg_dfg"}

    if not _is_readable_file(paths.error_json_path):
        raise FileNotFoundError(f"Cannot read error JSON: {paths.error_json_path}")

    if not _is_readable_dir(paths.benchmark_arm_input_dir):
        issues.append(f"source asm directory is not readable: {paths.benchmark_arm_input_dir}")

    if require_cfg and not _is_readable_dir(paths.cfg_dir):
        issues.append(f"CFG directory is not readable: {paths.cfg_dir}")

    if require_dfg and not _is_readable_dir(paths.dfg_dir):
        issues.append(f"DFG directory is not readable: {paths.dfg_dir}")

    if not _is_readable_file(RUN_ERROR_JSON_SCRIPT):
        issues.append(f"validation script is missing/unreadable: {RUN_ERROR_JSON_SCRIPT}")

    if not _is_readable_dir(INPUT_TEST_DIR):
        issues.append(f"test root directory is not readable: {INPUT_TEST_DIR}")

    if shutil.which(args.clang) is None:
        issues.append(f"clang executable not found on PATH: {args.clang}")

    if shutil.which(args.qemu) is None:
        issues.append(f"qemu executable not found on PATH: {args.qemu}")

    if args.sysroot is not None and not _is_readable_dir(args.sysroot):
        issues.append(f"sysroot directory is not readable: {args.sysroot}")

    try:
        payload = json.loads(paths.error_json_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise RuntimeError(f"Failed to parse error JSON {paths.error_json_path}: {exc}") from exc

    errored = payload.get("errored_problems", [])
    if not isinstance(errored, list):
        raise RuntimeError("Invalid error JSON format: 'errored_problems' must be a list")

    specs: list[ProblemSpec] = []
    for entry in errored:
        problem_name = str(entry.get("name", "")).strip()
        if not problem_name:
            issues.append("Found errored_problems entry with empty 'name'")
            continue

        source_matches = sorted(paths.benchmark_arm_input_dir.glob(f"{problem_name}_*.s"))
        if not source_matches:
            issues.append(
                f"missing source asm for {problem_name}: expected {paths.benchmark_arm_input_dir / (problem_name + '_*.s')}"
            )
            continue
        source_asm = source_matches[0]
        if not _is_readable_file(source_asm):
            issues.append(f"source asm is not readable for {problem_name}: {source_asm}")
            continue

        cfg_path = resolve_graph_path(paths.cfg_dir, problem_name, "cfg")
        dfg_path = resolve_graph_path(paths.dfg_dir, problem_name, "dfg")

        if require_cfg and (cfg_path is None or not _is_readable_file(cfg_path)):
            issues.append(
                f"missing/unreadable CFG for {problem_name}: expected {problem_name}_cfg.* or {problem_name}_*_cfg.* in {paths.cfg_dir}"
            )

        if require_dfg and (dfg_path is None or not _is_readable_file(dfg_path)):
            issues.append(
                f"missing/unreadable DFG for {problem_name}: expected {problem_name}_dfg.* or {problem_name}_*_dfg.* in {paths.dfg_dir}"
            )

        # Keep predictable fallback paths for reporting/prompt sections when optional files are absent.
        if cfg_path is None:
            cfg_path = paths.cfg_dir / f"{problem_name}_cfg.txt"
        if dfg_path is None:
            dfg_path = paths.dfg_dir / f"{problem_name}_dfg.txt"

        specs.append(
            ProblemSpec(
                name=problem_name,
                summary=str(entry.get("summary", "")),
                stderr=str(entry.get("stderr", "")),
                source_asm_path=source_asm,
                source_asm_name=source_asm.name,
                cfg_path=cfg_path,
                dfg_path=dfg_path,
            )
        )

    if issues:
        detail = "\n".join(f"- {item}" for item in issues)
        raise RuntimeError(
            "Preflight validation failed. Terminating before execution.\n"
            f"{detail}"
        )

    return specs


def build_prompt(
    problem: ProblemSpec,
    source_asm: str,
    prompt_config: str,
    cfg_text: str,
    dfg_text: str,
    source_language: str,
    cfg_language: str,
    dfg_language: str,
) -> str:
    sections: list[str] = [
        f"Repair the following translated {source_language} assembly function.",
        "",
        "Goal:",
        (
            f"Produce a corrected {source_language} assembly function that preserves behavior"
        ),
        "",
        "Hard requirements:",
        "- Output only assembly text. No markdown fences. No prose.",
        "- Keep function signature/name expectations used by the harness (func0 unless explicitly required otherwise).",
        "- Keep the same target ISA/language as input; do not translate to a different ISA.",
        "- Preserve exact semantics and edge cases.",
        (
            "- If CFG/DFG are provided, treat them as semantic guidance only; they may be from "
            "a different language than the target assembly."
        ),
        "",
    ]

    if prompt_config in {"error_only", "error_cfg", "error_dfg", "error_cfg_dfg"}:
        sections.extend(
            [
                "Known failure summary from prior validation:",
                problem.summary or "(no summary provided)",
                "",
                "Known stderr from prior validation:",
                problem.stderr or "(no stderr provided)",
                "",
            ]
        )

    sections.extend([f"Input {source_language} Assembly:", source_asm, ""])

    if prompt_config in {"cfg_only", "error_cfg", "cfg_dfg", "error_cfg_dfg"}:
        sections.extend(
            [
                f"CFG ({cfg_language} semantic graph; target output remains {source_language} assembly):",
                cfg_text or "(CFG file not found)",
                "",
            ]
        )

    if prompt_config in {"dfg_only", "error_dfg", "cfg_dfg", "error_cfg_dfg"}:
        sections.extend(
            [
                f"DFG ({dfg_language} semantic graph; target output remains {source_language} assembly):",
                dfg_text or "(DFG file not found)",
                "",
            ]
        )

    sections.append("Return only the final corrected assembly text.")
    return "\n".join(sections)


async def call_gemini_with_retry(
    aclient: genai.client.AsyncClient,
    prompt: str,
    problem_name: str,
    model_name: str,
    max_retries: int,
    retry_base_seconds: float,
) -> str:
    last_error: Exception | None = None

    for attempt in range(1, max_retries + 1):
        try:
            _log(f"{problem_name}: sending request (attempt {attempt}/{max_retries})")
            response = await aclient.models.generate_content(model=model_name, contents=prompt)
            _log(f"{problem_name}: response received")
            return response.text if response.text else ""
        except Exception as exc:
            error_text = str(exc)
            if _is_daily_quota_exhausted(error_text):
                raise QuotaExhaustedError(
                    problem_name=problem_name,
                    retry_delay_seconds=_extract_retry_delay_seconds(error_text),
                    raw_error=error_text,
                ) from exc

            last_error = exc
            if attempt == max_retries:
                break

            backoff = retry_base_seconds * (2 ** (attempt - 1)) + random.uniform(0.0, 0.25)
            _log(
                f"{problem_name}: attempt {attempt}/{max_retries} failed ({exc}); "
                f"retrying after {backoff:.2f}s"
            )
            await asyncio.sleep(backoff)

    if last_error is None:
        raise RuntimeError(f"Unknown model error while processing {problem_name}")
    raise last_error


def validate_single_problem(
    paths: ComposerRuntimePaths,
    args: argparse.Namespace,
    problem_name: str,
    attempt: int,
) -> tuple[bool, str]:
    validation_json_path = paths.validation_json_dir / f"{problem_name}_attempt{attempt}.json"
    probe_log_path = paths.compile_probe_dir / f"{problem_name}_attempt{attempt}.log"

    command = [
        sys.executable,
        str(RUN_ERROR_JSON_SCRIPT),
        str(paths.fixed_asm_dir),
        "--problems",
        problem_name,
        "--test-root",
        str(INPUT_TEST_DIR),
        "--clang",
        args.clang,
        "--qemu",
        args.qemu,
        "--timeout",
        str(args.timeout),
        "--output",
        str(validation_json_path),
    ]
    if args.sysroot:
        command.extend(["--sysroot", str(args.sysroot)])
    if args.no_link_math:
        command.append("--no-link-math")

    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    _write_text(
        probe_log_path,
        "\n".join(
            [
                f"command: {' '.join(command)}",
                f"returncode: {completed.returncode}",
                "stdout:",
                completed.stdout,
                "stderr:",
                completed.stderr,
            ]
        ),
    )

    if not validation_json_path.exists():
        return False, "Validation JSON was not generated"

    payload = json.loads(validation_json_path.read_text(encoding="utf-8"))
    errored_count = int(payload.get("errored_count", 0))
    problems_processed = int(payload.get("problems_processed", 0))
    if errored_count == 0 and problems_processed > 0:
        return True, "Passed validation"

    errored_problems = payload.get("errored_problems", [])
    if errored_problems:
        first = errored_problems[0]
        return False, f"{first.get('status', 'error')}: {first.get('summary', '')}".strip()
    return False, f"Validation reported {errored_count} errors"


def validate_all_fixed_outputs(paths: ComposerRuntimePaths, args: argparse.Namespace) -> tuple[Path, int]:
    final_json_path = paths.validation_json_dir / "final_error_problems.json"
    command = [
        sys.executable,
        str(RUN_ERROR_JSON_SCRIPT),
        str(paths.fixed_asm_dir),
        "--test-root",
        str(INPUT_TEST_DIR),
        "--clang",
        args.clang,
        "--qemu",
        args.qemu,
        "--timeout",
        str(args.timeout),
        "--output",
        str(final_json_path),
    ]
    if args.sysroot:
        command.extend(["--sysroot", str(args.sysroot)])
    if args.no_link_math:
        command.append("--no-link-math")

    subprocess.run(command, capture_output=True, text=True, check=False)
    if not final_json_path.exists():
        return final_json_path, -1

    payload = json.loads(final_json_path.read_text(encoding="utf-8"))
    return final_json_path, int(payload.get("errored_count", 0))


async def process_one_problem(
    problem: ProblemSpec,
    paths: ComposerRuntimePaths,
    args: argparse.Namespace,
    aclient: genai.client.AsyncClient,
    results: list[ProblemResult],
    result_lock: asyncio.Lock,
    progress: dict[str, int],
    progress_lock: asyncio.Lock,
) -> None:
    problem_name = problem.name
    source_asm = await asyncio.to_thread(_read_text, problem.source_asm_path)
    cfg_text = ""
    dfg_text = ""
    if problem.cfg_path.exists():
        cfg_text = await asyncio.to_thread(_read_text, problem.cfg_path)
    if problem.dfg_path.exists():
        dfg_text = await asyncio.to_thread(_read_text, problem.dfg_path)

    # Copy original errored asm once into run directory, unchanged.
    original_copy_path = paths.original_error_asm_dir / problem.source_asm_name
    if not original_copy_path.exists():
        await asyncio.to_thread(shutil.copy2, problem.source_asm_path, original_copy_path)

    fixed_asm_path = paths.fixed_asm_dir / problem.source_asm_name
    attempt_records: list[dict[str, object]] = []
    final_note = "Unknown"
    succeeded = False

    for attempt in range(1, args.max_retries + 1):
        _log(f"{problem_name}: repair attempt {attempt}/{args.max_retries}")
        prompt = build_prompt(
            problem=problem,
            source_asm=source_asm,
            prompt_config=args.prompt_config,
            cfg_text=cfg_text,
            dfg_text=dfg_text,
            source_language=paths.source_language,
            cfg_language=paths.cfg_language,
            dfg_language=paths.dfg_language,
        )
        prompt_path = paths.prompts_dir / f"{problem_name}_attempt{attempt}.txt"
        await asyncio.to_thread(_write_text, prompt_path, prompt)

        try:
            raw_output = await call_gemini_with_retry(
                aclient=aclient,
                prompt=prompt,
                problem_name=problem_name,
                model_name=args.model,
                max_retries=args.max_retries,
                retry_base_seconds=args.retry_base_seconds,
            )
        except Exception as exc:
            record = {
                "attempt": attempt,
                "status": "model_error",
                "note": str(exc),
            }
            attempt_records.append(record)
            final_note = str(exc)
            if isinstance(exc, QuotaExhaustedError):
                raise
            continue

        raw_path = paths.raw_output_dir / f"{problem_name}_attempt{attempt}.txt"
        await asyncio.to_thread(_write_text, raw_path, raw_output)

        cleaned, diagnostics = clean_model_output(raw_output)
        cleaned_path = paths.cleaned_output_dir / f"{problem_name}_attempt{attempt}.txt"
        diag_path = paths.clean_diagnostics_dir / f"{problem_name}_attempt{attempt}.json"
        await asyncio.to_thread(_write_text, cleaned_path, cleaned)
        await asyncio.to_thread(_write_text, diag_path, json.dumps(diagnostics, indent=2) + "\n")

        await asyncio.to_thread(_write_text, fixed_asm_path, cleaned)
        passed, note = await asyncio.to_thread(validate_single_problem, paths, args, problem_name, attempt)

        record = {
            "attempt": attempt,
            "status": "passed" if passed else "failed",
            "note": note,
            "prompt_path": str(prompt_path),
            "raw_output_path": str(raw_path),
            "cleaned_output_path": str(cleaned_path),
            "clean_diagnostics_path": str(diag_path),
        }
        attempt_records.append(record)
        final_note = note

        if passed:
            succeeded = True
            break

    result = ProblemResult(
        name=problem_name,
        source_asm_path=problem.source_asm_path,
        fixed_asm_path=fixed_asm_path,
        succeeded=succeeded,
        attempts_used=len(attempt_records),
        final_note=final_note,
        attempts=attempt_records,
    )

    async with result_lock:
        results.append(result)

    async with progress_lock:
        progress["done"] += 1
        label = "OK" if succeeded else "FAIL"
        print(f"[{progress['done']}/{progress['total']}] {label} {problem_name} | {final_note}")


async def worker_loop(
    worker_id: int,
    queue: asyncio.Queue[ProblemSpec],
    paths: ComposerRuntimePaths,
    args: argparse.Namespace,
    aclient: genai.client.AsyncClient,
    results: list[ProblemResult],
    result_lock: asyncio.Lock,
    progress: dict[str, int],
    progress_lock: asyncio.Lock,
    stop_event: asyncio.Event,
) -> None:
    _log(f"worker-{worker_id}: started")
    while True:
        if stop_event.is_set():
            return
        try:
            problem = queue.get_nowait()
        except asyncio.QueueEmpty:
            return
        try:
            await process_one_problem(
                problem=problem,
                paths=paths,
                args=args,
                aclient=aclient,
                results=results,
                result_lock=result_lock,
                progress=progress,
                progress_lock=progress_lock,
            )
        except QuotaExhaustedError as exc:
            stop_event.set()
            await asyncio.to_thread(
                _append_text,
                paths.logs_dir / "failures.log",
                f"GLOBAL: {exc}\n",
            )
            raise
        except Exception as exc:
            await asyncio.to_thread(
                _append_text,
                paths.logs_dir / "failures.log",
                f"{problem.name}: unhandled worker error: {exc}\n",
            )
        finally:
            queue.task_done()


async def periodic_progress_updates(
    progress: dict[str, int],
    progress_lock: asyncio.Lock,
    stop_event: asyncio.Event,
    interval_seconds: float = 30.0,
) -> None:
    """Emit periodic progress updates showing remaining problems."""

    while not stop_event.is_set():
        await asyncio.sleep(interval_seconds)
        if stop_event.is_set():
            return

        async with progress_lock:
            done = progress.get("done", 0)
            total = progress.get("total", 0)

        if done >= total:
            return

        remaining = max(total - done, 0)
        _log(f"Progress update: completed={done}/{total}, remaining={remaining}")


def write_reports(
    args: argparse.Namespace,
    paths: ComposerRuntimePaths,
    problems: list[ProblemSpec],
    results: list[ProblemResult],
    started_at: datetime,
    finished_at: datetime,
    final_validation_path: Path,
    final_validation_error_count: int,
) -> None:
    by_name = {result.name: result for result in results}

    processed_count = len(results)
    success_count = sum(1 for result in results if result.succeeded)
    fail_count = len(problems) - success_count
    missing_count = len(problems) - processed_count

    # Calculate total problems and overall success rate
    total_problems = len(list(paths.benchmark_arm_input_dir.glob("*.s")))
    overall_successful = total_problems - final_validation_error_count
    success_rate = (overall_successful / total_problems * 100) if total_problems > 0 else 0

    brief_lines = [
        f"Run started: {started_at.isoformat(timespec='seconds')}",
        f"Run finished: {finished_at.isoformat(timespec='seconds')}",
        f"Input experiment dir: {paths.input_experiment_dir}",
        f"Run label: {args.run_label or paths.input_experiment_dir.name}",
        f"Source language: {paths.source_language}",
        f"Model: {args.model}",
        f"Prompt config: {args.prompt_config}",
        f"Total problems in experiment: {total_problems}",
        f"Errored problems from input JSON: {len(problems)}",
        f"Composer processed: {processed_count}",
        f"Composer succeeded: {success_count}",
        f"Composer failed: {fail_count}",
        f"Composer missing/unprocessed: {missing_count}",
        f"Global Total Overall problems successfully passed: {overall_successful}/{total_problems} ({success_rate:.1f}%)",
        f"Final validation JSON: {final_validation_path}",
        f"Final validation errored count: {final_validation_error_count}",
        "",
        "Failed problems:",
    ]
    for result in sorted(results, key=lambda item: item.name):
        if not result.succeeded:
            brief_lines.append(f"- {result.name}: {result.final_note}")
    if fail_count == 0:
        brief_lines.append("- none")

    _write_text(paths.brief_report_path, "\n".join(brief_lines) + "\n")

    verbose_lines = list(brief_lines)
    verbose_lines.append("")
    verbose_lines.append("Per-problem details:")
    for problem in sorted(problems, key=lambda item: item.name):
        verbose_lines.append("")
        verbose_lines.append(f"Problem: {problem.name}")
        verbose_lines.append(f"Source asm: {problem.source_asm_path}")
        verbose_lines.append(f"CFG path: {problem.cfg_path}")
        verbose_lines.append(f"DFG path: {problem.dfg_path}")
        result = by_name.get(problem.name)
        if result is None:
            verbose_lines.append("Result: missing")
            continue
        verbose_lines.append(f"Succeeded: {result.succeeded}")
        verbose_lines.append(f"Attempts used: {result.attempts_used}")
        verbose_lines.append(f"Final note: {result.final_note}")
        verbose_lines.append(f"Fixed asm path: {result.fixed_asm_path}")
        verbose_lines.append("Attempts:")
        for attempt in result.attempts:
            verbose_lines.append(f"  - attempt {attempt.get('attempt')}: {attempt.get('status')} | {attempt.get('note')}")
            prompt_path = attempt.get("prompt_path")
            if prompt_path:
                verbose_lines.append(f"    prompt: {prompt_path}")
            raw_output_path = attempt.get("raw_output_path")
            if raw_output_path:
                verbose_lines.append(f"    raw: {raw_output_path}")
            cleaned_output_path = attempt.get("cleaned_output_path")
            if cleaned_output_path:
                verbose_lines.append(f"    cleaned: {cleaned_output_path}")
            diagnostics_path = attempt.get("clean_diagnostics_path")
            if diagnostics_path:
                verbose_lines.append(f"    diagnostics: {diagnostics_path}")

    _write_text(paths.verbose_report_path, "\n".join(verbose_lines) + "\n")


async def run_async(
    args: argparse.Namespace,
    paths: ComposerRuntimePaths,
    problems: list[ProblemSpec],
) -> tuple[list[ProblemResult], QuotaExhaustedError | None]:
    queue: asyncio.Queue[ProblemSpec] = asyncio.Queue()
    for problem in problems:
        queue.put_nowait(problem)

    results: list[ProblemResult] = []
    result_lock = asyncio.Lock()
    progress_lock = asyncio.Lock()
    progress = {"done": 0, "total": len(problems)}
    stop_event = asyncio.Event()

    worker_count = max(1, min(args.max_concurrency, len(problems)))
    _log(f"Opening async Gemini client with {worker_count} workers")
    async with genai.Client().aio as aclient:
        progress_task = asyncio.create_task(
            periodic_progress_updates(
                progress=progress,
                progress_lock=progress_lock,
                stop_event=stop_event,
                interval_seconds=30.0,
            )
        )
        tasks = [
            asyncio.create_task(
                worker_loop(
                    worker_id=index,
                    queue=queue,
                    paths=paths,
                    args=args,
                    aclient=aclient,
                    results=results,
                    result_lock=result_lock,
                    progress=progress,
                    progress_lock=progress_lock,
                    stop_event=stop_event,
                )
            )
            for index in range(1, worker_count + 1)
        ]
        quota_error: QuotaExhaustedError | None = None
        try:
            await asyncio.gather(*tasks)
        except QuotaExhaustedError as exc:
            quota_error = exc
            stop_event.set()
            for task in tasks:
                if not task.done():
                    task.cancel()
            await asyncio.gather(*tasks, return_exceptions=True)
        finally:
            stop_event.set()
            if not progress_task.done():
                progress_task.cancel()
            await asyncio.gather(progress_task, return_exceptions=True)

    return results, quota_error


def main() -> int:
    args = parse_args()
    try:
        paths = resolve_runtime_paths(args)
        problems = load_problem_specs(paths, args)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2

    # Create the folder layout used by the runtime only after preflight passes.
    paths.prompts_dir.mkdir(parents=True, exist_ok=True)
    paths.raw_output_dir.mkdir(parents=True, exist_ok=True)
    paths.original_error_asm_dir.mkdir(parents=True, exist_ok=True)
    paths.fixed_asm_dir.mkdir(parents=True, exist_ok=True)
    paths.logs_dir.mkdir(parents=True, exist_ok=True)
    paths.brief_report_path.parent.mkdir(parents=True, exist_ok=True)
    paths.cleaned_output_dir.mkdir(parents=True, exist_ok=True)
    paths.clean_diagnostics_dir.mkdir(parents=True, exist_ok=True)
    paths.compile_probe_dir.mkdir(parents=True, exist_ok=True)
    paths.validation_json_dir.mkdir(parents=True, exist_ok=True)

    started_at = datetime.now()

    print(f"Benchmark ARM input: {paths.benchmark_arm_input_dir}")
    print(f"Input experiment dir: {paths.input_experiment_dir}")
    print(f"Source language: {paths.source_language}")
    print(f"CFG language: {paths.cfg_language}")
    print(f"DFG language: {paths.dfg_language}")
    print(f"Error JSON: {paths.error_json_path}")
    print(f"Run output dir: {paths.run_output_dir}")
    print(f"Config source script: {RUN_ERROR_JSON_SCRIPT}")
    print(f"CFG dir: {paths.cfg_dir}")
    print(f"DFG dir: {paths.dfg_dir}")
    print(f"Test root: {INPUT_TEST_DIR}")
    print(f"Max concurrency: {args.max_concurrency}")
    print(f"Max retries: {args.max_retries}")
    print(f"Retry base seconds: {args.retry_base_seconds}")
    print(f"Problems to repair: {len(problems)}")

    if not problems:
        finished_at = datetime.now()
        final_validation_path, final_validation_error_count = validate_all_fixed_outputs(paths, args)
        write_reports(
            args=args,
            paths=paths,
            problems=problems,
            results=[],
            started_at=started_at,
            finished_at=finished_at,
            final_validation_path=final_validation_path,
            final_validation_error_count=final_validation_error_count,
        )
        print("No errored problems found in input JSON.")
        print(f"Brief report: {paths.brief_report_path}")
        print(f"Verbose report: {paths.verbose_report_path}")
        return 0

    results, quota_error = asyncio.run(run_async(args, paths, problems))

    finished_at = datetime.now()
    final_validation_path, final_validation_error_count = validate_all_fixed_outputs(paths, args)
    write_reports(
        args=args,
        paths=paths,
        problems=problems,
        results=results,
        started_at=started_at,
        finished_at=finished_at,
        final_validation_path=final_validation_path,
        final_validation_error_count=final_validation_error_count,
    )

    success_count = sum(1 for result in results if result.succeeded)
    fail_count = len(results) - success_count
    print(f"Composer finished. success={success_count} fail={fail_count}")
    print(f"Final validation JSON: {final_validation_path}")
    print(f"Final validation errored count: {final_validation_error_count}")
    print(f"Brief report: {paths.brief_report_path}")
    print(f"Verbose report: {paths.verbose_report_path}")
    if quota_error is not None:
        print(str(quota_error))
        return 2
    return 0 if fail_count == 0 and final_validation_error_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
