"""
OpenAI Composer for repairing translated assembly that failed validation.

Purpose:
- Read errored problems from an experiment JSON generated by run_arm_translation_error_json.py.
- Build prompts for only errored problems.
- Run model calls asynchronously with retries using the OpenAI Responses API.
- Re-run validation on fixed outputs.
- Emit a single consolidated run report.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

try:
    import openai
    from openai import AsyncOpenAI
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False

try:
    from datasets import load_dataset
    HAS_DATASETS = True
except ImportError:
    HAS_DATASETS = False

from composer_config import (
    DEFAULT_SOURCE_LANGUAGE,
    DEFAULT_MAX_CONCURRENCY,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_BASE_SECONDS,
    INPUT_TEST_DIR,
    PROMPT_CONFIGS,
    RUN_ERROR_JSON_SCRIPT,
    composer_fixed_asm_dir,
    composer_logs_dir,
    composer_original_error_asm_dir,
    composer_output_dir,
    composer_prompts_dir,
    composer_raw_output_dir,
    composer_reports_dir,
)

@dataclass(frozen=True)
class ComposerRuntimePaths:
    """All config-derived paths used by the composer runtime."""
    benchmark_asm_input_dir: Path
    input_experiment_dir: Path
    error_json_path: Path
    run_output_dir: Path
    prompts_dir: Path
    raw_output_dir: Path
    original_error_asm_dir: Path
    fixed_asm_dir: Path
    logs_dir: Path
    reports_dir: Path
    cleaned_output_dir: Path
    clean_diagnostics_dir: Path
    compile_probe_dir: Path
    validation_json_dir: Path
    source_language: str

@dataclass
class ProblemSpec:
    name: str
    summary: str
    stderr: str
    source_asm_path: Path
    source_asm_name: str
    cfg_text: str
    dfg_text: str

@dataclass
class ProblemResult:
    name: str
    source_asm_path: Path
    fixed_asm_path: Path
    succeeded: bool
    attempts_used: int
    final_note: str
    attempts: list[dict[str, object]]

def resolve_openai_api_key() -> tuple[str, str]:
    """Resolve API key from environment."""
    env_name = "OPENAI_API_KEY"
    value = os.environ.get(env_name)
    if not value:
        raise RuntimeError("OPENAI_API_KEY environment variable is missing.")
    return env_name, value.strip()

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="OpenAI Composer using JSON config")
    parser.add_argument(
        "input_dir",
        type=Path,
        help="Input experiment directory containing translated_asm and jsons",
    )
    parser.add_argument(
        "--config", 
        type=Path, 
        required=True, 
        help="Path to the SAME config.json used for the initial translation"
    )
    parser.add_argument("--prompt-config", help="Override prompt config strategy (e.g., error_cfg)")
    parser.add_argument("--run-label", help="Optional label used in output naming")
    return parser.parse_args()

def resolve_runtime_paths(args: argparse.Namespace) -> ComposerRuntimePaths:
    input_experiment_dir = args.input_dir.resolve()
    if not input_experiment_dir.exists() or not input_experiment_dir.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {input_experiment_dir}")

    # Fallback logic to find the translated assembly folder regardless of naming conventions
    benchmark_asm_input_dir = input_experiment_dir / "translated_asm"
    if not benchmark_asm_input_dir.exists() or not benchmark_asm_input_dir.is_dir():
        benchmark_asm_input_dir = input_experiment_dir / f"{args.source_language}_asm"
        if not benchmark_asm_input_dir.exists() or not benchmark_asm_input_dir.is_dir():
            raise FileNotFoundError(f"Source asm directory does not exist. Searched for 'translated_asm' or '{args.source_language}_asm' in {input_experiment_dir}")

    if args.error_json is not None:
        error_json_path = args.error_json.resolve()
    else:
        json_dir = input_experiment_dir / "jsons"
        candidates = []
        if json_dir.exists() and json_dir.is_dir():
            candidates = sorted(json_dir.glob("*_error_problems.json"), key=lambda p: p.stat().st_mtime)
        if not candidates:
            raise FileNotFoundError(f"No *_error_problems.json found in {json_dir}.")
        error_json_path = candidates[-1].resolve()

    run_label = args.run_label or input_experiment_dir.name
    run_output_dir = composer_output_dir(benchmark_name=run_label, model_name=args.model, prompt_config=args.prompt_config)

    return ComposerRuntimePaths(
        benchmark_asm_input_dir=benchmark_asm_input_dir,
        input_experiment_dir=input_experiment_dir,
        error_json_path=error_json_path,
        run_output_dir=run_output_dir,
        prompts_dir=composer_prompts_dir(run_output_dir),
        raw_output_dir=composer_raw_output_dir(run_output_dir),
        original_error_asm_dir=composer_original_error_asm_dir(run_output_dir, args.source_language),
        fixed_asm_dir=composer_fixed_asm_dir(run_output_dir, args.source_language),
        logs_dir=composer_logs_dir(run_output_dir),
        reports_dir=composer_reports_dir(run_output_dir),
        cleaned_output_dir=run_output_dir / "cleaned_model_output",
        clean_diagnostics_dir=run_output_dir / "clean_diagnostics",
        compile_probe_dir=run_output_dir / "compile_probe",
        validation_json_dir=run_output_dir / "validation_json",
        source_language=args.source_language,
    )

def _log(message: str) -> None:
    now = time.strftime("%H:%M:%S")
    print(f"[{now}] {message}")

def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")

def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def _append_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(content)

def _is_asm_like_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped: return True
    if stripped.startswith((".", "//", "/*", "*", "#")): return True
    if re.match(r"^[A-Za-z_.$][\w.$]*:\s*$", stripped): return True
    if re.match(r"^b(\.[A-Za-z0-9]+)?\b", stripped): return True
    if re.match(r"^[a-z]{2,8}(\.[A-Za-z0-9]+)?\b", stripped): return True
    return False

def clean_model_output(text: str) -> tuple[str, dict[str, object]]:
    """Strip common markdown/prose wrappers and return diagnostics."""
    raw = text or ""
    lines = raw.splitlines()
    without_fences = [line for line in lines if not line.strip().startswith("```")]

    first_idx = 0
    while first_idx < len(without_fences) and not _is_asm_like_line(without_fences[first_idx]):
        first_idx += 1

    last_idx = len(without_fences) - 1
    while last_idx >= first_idx and not _is_asm_like_line(without_fences[last_idx]):
        last_idx -= 1

    if first_idx <= last_idx:
        cleaned_lines = without_fences[first_idx : last_idx + 1]
    else:
        cleaned_lines = []

    cleaned = "\n".join(cleaned_lines).strip()
    diagnostics = {
        "raw_line_count": len(lines),
        "fence_lines_removed": len(lines) - len(without_fences),
        "leading_non_asm_lines_removed": first_idx,
        "trailing_non_asm_lines_removed": max(0, len(without_fences) - last_idx - 1) if without_fences else 0,
        "cleaned_line_count": len(cleaned_lines),
        "is_empty_after_clean": cleaned == "",
    }
    return cleaned, diagnostics

def fetch_hf_graph_data(dataset_id: str, column: str, hf_token: str | None) -> dict[str, str]:
    """Fetches CFG/DFG data from Hugging Face and returns a map of task_name -> graph_text."""
    if not HAS_DATASETS:
        raise ImportError("The 'datasets' library is required. Install with: pip install datasets")
    
    _log(f"Fetching Hugging Face dataset: {dataset_id} (column: {column})")
    ds = load_dataset(dataset_id, split="train", token=hf_token)
    
    graph_map = {}
    for row in ds:
        task_name = row["task_name"]
        if column not in row:
            raise KeyError(f"Column '{column}' not found in dataset {dataset_id}.")
        graph_map[task_name] = str(row[column])
        
    return graph_map

def _is_readable_file(path: Path) -> bool:
    if not path.exists() or not path.is_file(): return False
    try:
        with path.open("r", encoding="utf-8"): return True
    except OSError: return False

def _is_readable_dir(path: Path) -> bool:
    if not path.exists() or not path.is_dir(): return False
    try:
        next(path.iterdir(), None)
        return True
    except OSError: return False

def load_problem_specs(paths: ComposerRuntimePaths, args: argparse.Namespace, cfg_data: dict[str, str], dfg_data: dict[str, str]) -> list[ProblemSpec]:
    issues: list[str] = []
    require_cfg = args.prompt_config in {"cfg_only", "error_cfg", "cfg_dfg", "error_cfg_dfg"}
    require_dfg = args.prompt_config in {"dfg_only", "error_dfg", "cfg_dfg", "error_cfg_dfg"}

    if not _is_readable_file(paths.error_json_path): issues.append(f"Cannot read error JSON: {paths.error_json_path}")
    if not _is_readable_dir(paths.benchmark_asm_input_dir): issues.append(f"source asm directory is not readable: {paths.benchmark_asm_input_dir}")
    if not _is_readable_file(RUN_ERROR_JSON_SCRIPT): issues.append(f"validation script is missing/unreadable: {RUN_ERROR_JSON_SCRIPT}")
    if not _is_readable_dir(INPUT_TEST_DIR): issues.append(f"test root directory is not readable: {INPUT_TEST_DIR}")

    try:
        payload = json.loads(paths.error_json_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise RuntimeError(f"Failed to parse error JSON {paths.error_json_path}: {exc}") from exc

    errored = payload.get("errored_problems", [])
    specs: list[ProblemSpec] = []
    
    for entry in errored:
        problem_name = str(entry.get("name", "")).strip()
        if not problem_name: continue

        source_matches = sorted(paths.benchmark_asm_input_dir.glob(f"{problem_name}_*.s"))
        if not source_matches:
            issues.append(f"missing source asm for {problem_name} in {paths.benchmark_asm_input_dir}")
            continue
        source_asm = source_matches[0]

        cfg_text = cfg_data.get(problem_name, "")
        if require_cfg and not cfg_text:
            issues.append(f"missing CFG in HF dataset for {problem_name}")
            
        dfg_text = dfg_data.get(problem_name, "")
        if require_dfg and not dfg_text:
            issues.append(f"missing DFG in HF dataset for {problem_name}")

        specs.append(
            ProblemSpec(
                name=problem_name,
                summary=str(entry.get("summary", "")),
                stderr=str(entry.get("stderr", "")),
                source_asm_path=source_asm,
                source_asm_name=source_asm.name,
                cfg_text=cfg_text,
                dfg_text=dfg_text,
            )
        )

    if issues:
        detail = "\n".join(f"- {item}" for item in issues)
        raise RuntimeError(f"Preflight validation failed. Terminating before execution.\n{detail}")

    return specs

def build_prompt(problem: ProblemSpec, source_asm: str, prompt_config: str, source_language: str, cfg_language: str, dfg_language: str) -> str:
    sections: list[str] = [
        f"Repair the following translated {source_language} assembly function.",
        "",
        "Goal:",
        f"Produce a corrected {source_language} assembly function that preserves behavior",
        "",
        "Hard requirements:",
        "- Output only assembly text. No markdown fences. No prose.",
        "- Keep function signature/name expectations used by the harness (func0 unless explicitly required otherwise).",
        "- Keep the same target ISA/language as input; do not translate to a different ISA.",
        "- Preserve exact semantics and edge cases.",
        "- If CFG/DFG are provided, treat them as semantic guidance only",
        "",
    ]

    if prompt_config in {"error_only", "error_cfg", "error_dfg", "error_cfg_dfg"}:
        sections.extend([
            "Known failure summary from prior validation:",
            problem.summary or "(no summary provided)",
            "",
            "Known stderr from prior validation:",
            problem.stderr or "(no stderr provided)",
            "",
        ])

    sections.extend([f"Input {source_language} Assembly:", source_asm, ""])

    if prompt_config in {"cfg_only", "error_cfg", "cfg_dfg", "error_cfg_dfg"}:
        sections.extend([
            f"CFG ({cfg_language} semantic graph; target output remains {source_language} assembly):",
            problem.cfg_text or "(CFG data not found)",
            "",
        ])

    if prompt_config in {"dfg_only", "error_dfg", "cfg_dfg", "error_cfg_dfg"}:
        sections.extend([
            f"DFG ({dfg_language} semantic graph; target output remains {source_language} assembly):",
            problem.dfg_text or "(DFG data not found)",
            "",
        ])

    sections.append("Return only the final corrected assembly text.")
    return "\n".join(sections)

async def call_openai_with_retry(aclient: AsyncOpenAI, prompt: str, problem_name: str, model_name: str, max_retries: int, retry_base_seconds: float) -> str:
    """Execute OpenAI request using the Responses API with retry/backoff."""
    for attempt in range(1, max_retries + 1):
        try:
            _log(f"{problem_name}: sending request (attempt {attempt}/{max_retries})")
            resp = await aclient.responses.create(
                model=model_name,
                instructions="You are an expert assembly repair assistant.\n- Output ONLY assembly\n- No comments\n- Preserve semantics exactly\n",
                input=prompt,
                timeout=120.0
            )
            _log(f"{problem_name}: response received")
            return resp.output_text or ""
        except openai.RateLimitError as e:
            if e.code == "insufficient_quota":
                _log(f"CRITICAL: OpenAI API Quota Exhausted while processing {problem_name}. Aborting entire run.")
                os._exit(1)
                
            if attempt == max_retries: raise
            sleep_time = retry_base_seconds * (2 ** (attempt - 1)) + random.uniform(0, 0.5)
            _log(f"{problem_name}: Rate limit hit, backing off for {sleep_time:.1f}s... (Attempt {attempt}/{max_retries})")
            await asyncio.sleep(sleep_time)
        except Exception as e:
            if attempt == max_retries: raise
            sleep_time = retry_base_seconds * (2 ** (attempt - 1))
            _log(f"{problem_name}: API Error [{type(e).__name__}]: {str(e)}. Retrying in {sleep_time}s... (Attempt {attempt}/{max_retries})")
            await asyncio.sleep(sleep_time)
    return ""

def validate_single_problem(paths: ComposerRuntimePaths, args: argparse.Namespace, problem_name: str, attempt: int) -> tuple[bool, str]:
    validation_json_path = paths.validation_json_dir / f"{problem_name}_attempt{attempt}.json"
    probe_log_path = paths.compile_probe_dir / f"{problem_name}_attempt{attempt}.log"

    command = [
        sys.executable, str(RUN_ERROR_JSON_SCRIPT), str(paths.fixed_asm_dir),
        "--problems", problem_name,
        "--test-root", str(INPUT_TEST_DIR),
        "--clang", args.clang,
        "--timeout", str(args.timeout),
        "--output", str(validation_json_path),
    ]
    if args.qemu: command.extend(["--qemu", args.qemu])
    if args.sysroot: command.extend(["--sysroot", str(args.sysroot)])
    if args.no_link_math: command.append("--no-link-math")

    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    _write_text(probe_log_path, "\n".join([
        f"command: {' '.join(command)}", f"returncode: {completed.returncode}",
        "stdout:\n" + completed.stdout, "stderr:\n" + completed.stderr,
    ]))

    if not validation_json_path.exists():
        return False, "Validation JSON was not generated"

    payload = json.loads(validation_json_path.read_text(encoding="utf-8"))
    errored_count = int(payload.get("errored_count", 0))
    problems_processed = int(payload.get("problems_processed", 0))
    if errored_count == 0 and problems_processed > 0:
        return True, "Passed validation"

    errored_problems = payload.get("errored_problems", [])
    if errored_problems:
        first = errored_problems[0]
        return False, f"{first.get('status', 'error')}: {first.get('summary', '')}".strip()
    return False, f"Validation reported {errored_count} errors"

def validate_all_fixed_outputs(paths: ComposerRuntimePaths, args: argparse.Namespace) -> tuple[Path, int]:
    final_json_path = paths.validation_json_dir / "final_error_problems.json"
    command = [
        sys.executable, str(RUN_ERROR_JSON_SCRIPT), str(paths.fixed_asm_dir),
        "--test-root", str(INPUT_TEST_DIR),
        "--clang", args.clang,
        "--timeout", str(args.timeout),
        "--output", str(final_json_path),
    ]
    if args.qemu: command.extend(["--qemu", args.qemu])
    if args.sysroot: command.extend(["--sysroot", str(args.sysroot)])
    if args.no_link_math: command.append("--no-link-math")

    subprocess.run(command, capture_output=True, text=True, check=False)
    if not final_json_path.exists():
        return final_json_path, -1

    payload = json.loads(final_json_path.read_text(encoding="utf-8"))
    return final_json_path, int(payload.get("errored_count", 0))

async def process_one_problem(
    problem: ProblemSpec, paths: ComposerRuntimePaths, args: argparse.Namespace, aclient: AsyncOpenAI,
    results: list[ProblemResult], result_lock: asyncio.Lock, progress: dict[str, int], progress_lock: asyncio.Lock
) -> None:
    problem_name = problem.name
    source_asm = await asyncio.to_thread(_read_text, problem.source_asm_path)

    original_copy_path = paths.original_error_asm_dir / problem.source_asm_name
    if not original_copy_path.exists():
        await asyncio.to_thread(shutil.copy2, problem.source_asm_path, original_copy_path)

    fixed_asm_path = paths.fixed_asm_dir / problem.source_asm_name
    attempt_records: list[dict[str, object]] = []
    final_note = "Unknown"
    succeeded = False

    for attempt in range(1, args.max_retries + 1):
        _log(f"{problem_name}: repair attempt {attempt}/{args.max_retries}")
        prompt = build_prompt(
            problem=problem, source_asm=source_asm, prompt_config=args.prompt_config,
            source_language=paths.source_language, cfg_language=args.cfg_language, dfg_language=args.dfg_language,
        )
        prompt_path = paths.prompts_dir / f"{problem_name}_attempt{attempt}.txt"
        await asyncio.to_thread(_write_text, prompt_path, prompt)

        try:
            raw_output = await call_openai_with_retry(
                aclient=aclient, prompt=prompt, problem_name=problem_name, model_name=args.model,
                max_retries=args.max_retries, retry_base_seconds=args.retry_base_seconds,
            )
        except Exception as exc:
            record = {"attempt": attempt, "status": "model_error", "note": str(exc)}
            attempt_records.append(record)
            final_note = str(exc)
            continue

        raw_path = paths.raw_output_dir / f"{problem_name}_attempt{attempt}.txt"
        await asyncio.to_thread(_write_text, raw_path, raw_output)

        cleaned, diagnostics = clean_model_output(raw_output)
        cleaned_path = paths.cleaned_output_dir / f"{problem_name}_attempt{attempt}.txt"
        diag_path = paths.clean_diagnostics_dir / f"{problem_name}_attempt{attempt}.json"
        await asyncio.to_thread(_write_text, cleaned_path, cleaned)
        await asyncio.to_thread(_write_text, diag_path, json.dumps(diagnostics, indent=2) + "\n")

        await asyncio.to_thread(_write_text, fixed_asm_path, cleaned)
        passed, note = await asyncio.to_thread(validate_single_problem, paths, args, problem_name, attempt)

        record = {
            "attempt": attempt, "status": "passed" if passed else "failed", "note": note,
            "prompt_path": str(prompt_path), "raw_output_path": str(raw_path),
            "cleaned_output_path": str(cleaned_path), "clean_diagnostics_path": str(diag_path),
        }
        attempt_records.append(record)
        final_note = note

        if passed:
            succeeded = True
            break

    result = ProblemResult(
        name=problem_name, source_asm_path=problem.source_asm_path, fixed_asm_path=fixed_asm_path,
        succeeded=succeeded, attempts_used=len(attempt_records), final_note=final_note, attempts=attempt_records,
    )

    async with result_lock: results.append(result)
    async with progress_lock:
        progress["done"] += 1
        label = "OK" if succeeded else "FAIL"
        print(f"[{progress['done']}/{progress['total']}] {label} {problem_name} | {final_note}")

async def worker_loop(
    worker_id: int, queue: asyncio.Queue[ProblemSpec], paths: ComposerRuntimePaths, args: argparse.Namespace,
    aclient: AsyncOpenAI, results: list[ProblemResult], result_lock: asyncio.Lock,
    progress: dict[str, int], progress_lock: asyncio.Lock, stop_event: asyncio.Event
) -> None:
    _log(f"worker-{worker_id}: started")
    while not stop_event.is_set():
        try: problem = queue.get_nowait()
        except asyncio.QueueEmpty: return
        try:
            await process_one_problem(problem, paths, args, aclient, results, result_lock, progress, progress_lock)
        except Exception as exc:
            await asyncio.to_thread(_append_text, paths.logs_dir / "failures.log", f"{problem.name}: unhandled worker error: {exc}\n")
        finally:
            queue.task_done()

async def periodic_progress_updates(progress: dict[str, int], progress_lock: asyncio.Lock, stop_event: asyncio.Event, interval_seconds: float = 30.0) -> None:
    while not stop_event.is_set():
        await asyncio.sleep(interval_seconds)
        if stop_event.is_set(): return
        async with progress_lock:
            done, total = progress.get("done", 0), progress.get("total", 0)
        if done >= total: return
        _log(f"Progress update: completed={done}/{total}, remaining={max(total - done, 0)}")

def write_reports(
    args: argparse.Namespace, paths: ComposerRuntimePaths, problems: list[ProblemSpec], results: list[ProblemResult],
    started_at: datetime, finished_at: datetime, final_validation_path: Path, final_validation_error_count: int
) -> None:
    by_name = {result.name: result for result in results}
    processed_count = len(results)
    success_count = sum(1 for result in results if result.succeeded)
    fail_count = len(problems) - success_count

    total_problems = len(list(paths.benchmark_asm_input_dir.glob("*.s")))
    overall_successful = total_problems - final_validation_error_count
    success_rate = (overall_successful / total_problems * 100) if total_problems > 0 else 0

    lines = [
        f"Run started: {started_at.isoformat(timespec='seconds')}",
        f"Run finished: {finished_at.isoformat(timespec='seconds')}",
        f"Input experiment dir: {paths.input_experiment_dir.absolute()}",
        f"Run label: {args.run_label or paths.input_experiment_dir.name}",
        f"Source language: {paths.source_language}",
        f"Model: {args.model}",
        f"Prompt config: {args.prompt_config}",
        f"Translator: Multi-pass Composer ({args.prompt_config} iterative refinement)",
        f"Total problems in experiment: {total_problems}",
        f"Errored problems processed: {len(problems)}",
        f"Composer succeeded: {success_count}",
        f"Composer failed: {fail_count}",
        f"Global Total Overall problems successfully passed: {overall_successful}/{total_problems} ({success_rate:.1f}%)",
        f"Final validation JSON: {final_validation_path}",
        "",
        "Failed problems (Post-Composer):",
    ]
    for result in sorted(results, key=lambda item: item.name):
        if not result.succeeded: lines.append(f"- {result.name}: {result.final_note}")
    if fail_count == 0: lines.append("- none")

    if results:
        lines.extend(["", "========================================", "--- Per Problem Details ---", "========================================"])
        for problem in sorted(problems, key=lambda item: item.name):
            lines.extend(["", f"Problem: {problem.name}", f"Source asm: {problem.source_asm_path}"])
            result = by_name.get(problem.name)
            if not result:
                lines.append("Result: missing")
                continue
            lines.extend([
                f"Succeeded: {result.succeeded}",
                f"Attempts used: {result.attempts_used}",
                f"Final note: {result.final_note}",
                f"Fixed asm path: {result.fixed_asm_path}",
                "Attempts:"
            ])
            for attempt in result.attempts:
                lines.append(f"  - attempt {attempt.get('attempt')}: {attempt.get('status')} | {attempt.get('note')}")

    timestamp = finished_at.strftime("%Y%m%d_%H%M%S")
    report_path = paths.reports_dir / f"{timestamp}_report.txt"
    _write_text(report_path, "\n".join(lines) + "\n")
    _log(f"Report written to {report_path}")

async def run_async(args: argparse.Namespace, paths: ComposerRuntimePaths, problems: list[ProblemSpec], api_key: str) -> list[ProblemResult]:
    queue: asyncio.Queue[ProblemSpec] = asyncio.Queue()
    for p in problems: queue.put_nowait(p)

    results: list[ProblemResult] = []
    result_lock = asyncio.Lock()
    progress_lock = asyncio.Lock()
    progress = {"done": 0, "total": len(problems)}
    stop_event = asyncio.Event()

    worker_count = max(1, min(args.max_concurrency, len(problems)))
    _log(f"Opening async OpenAI client with {worker_count} workers")
    
    aclient = AsyncOpenAI(api_key=api_key)
    progress_task = asyncio.create_task(periodic_progress_updates(progress, progress_lock, stop_event))
    tasks = [asyncio.create_task(worker_loop(i, queue, paths, args, aclient, results, result_lock, progress, progress_lock, stop_event)) for i in range(1, worker_count + 1)]
    
    try:
        await asyncio.gather(*tasks)
    finally:
        stop_event.set()
        if not progress_task.done(): progress_task.cancel()
        await asyncio.gather(progress_task, return_exceptions=True)

    return results

def main() -> int:
    args = parse_args()
    if not HAS_OPENAI:
        print("Install openai package: pip install openai", file=sys.stderr)
        return 2

    try:
        api_key_source, api_key = resolve_openai_api_key()
        
        # --- Inject JSON config into args ---
        cfg = json.loads(args.config.read_text(encoding="utf-8"))
        
        # The assembly we are repairing is the TARGET of the original translation
        args.source_language = cfg.get("target_arch", "Armv8")
        
        # Pull specific columns from Hugging Face based on config
        args.cfg_language = cfg.get("cfg_dataset_column", cfg.get("source_dataset_column", "x86_64"))
        args.dfg_language = cfg.get("dfg_dataset_column", cfg.get("source_dataset_column", "x86_64"))
        
        # API and Prompt config
        args.model = cfg.get("composer_model", cfg.get("model_name", "gpt-5-mini-2025-08-07"))
        args.prompt_config = args.prompt_config or cfg.get("composer_prompt_config", "base")
        
        # Validation Execution flags
        args.clang = cfg.get("clang", "clang-17")
        args.timeout = cfg.get("timeout_seconds", 30)
        
        # Properly handle QEMU vs Native based on the config
        args.qemu = cfg.get("qemu", "") if cfg.get("use_qemu", True) else ""
        
        # Concurrency and Retries
        args.max_concurrency = cfg.get("max_workers", 20)
        args.max_retries = cfg.get("max_retries", 3)
        args.retry_base_seconds = cfg.get("retry_base_seconds", 2.0)
        
        # Hardcoded defaults for obscure linking flags
        args.no_link_math = False
        args.sysroot = None
        args.error_json = getattr(args, "error_json", None)
        # -----------------------------------------

        paths = resolve_runtime_paths(args)
        
        # HF Authentication
        hf_token = cfg.get("hf_token") or os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN")

        # Fetch Data based on prompt config
        require_cfg = args.prompt_config in {"cfg_only", "error_cfg", "cfg_dfg", "error_cfg_dfg"}
        require_dfg = args.prompt_config in {"dfg_only", "error_dfg", "cfg_dfg", "error_cfg_dfg"}

        cfg_data: dict[str, str] = {}
        dfg_data: dict[str, str] = {}
        
        if require_cfg:
            cfg_data = fetch_hf_graph_data("ryaasabsar/humaneval_asm_cfg", args.cfg_language, hf_token)
        if require_dfg:
            dfg_data = fetch_hf_graph_data("ryaasabsar/humaneval_asm_dfg", args.dfg_language, hf_token)
            
        problems = load_problem_specs(paths, args, cfg_data, dfg_data)
        
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2

    paths.prompts_dir.mkdir(parents=True, exist_ok=True)
    paths.raw_output_dir.mkdir(parents=True, exist_ok=True)
    paths.original_error_asm_dir.mkdir(parents=True, exist_ok=True)
    paths.fixed_asm_dir.mkdir(parents=True, exist_ok=True)
    paths.logs_dir.mkdir(parents=True, exist_ok=True)
    paths.reports_dir.mkdir(parents=True, exist_ok=True)
    paths.cleaned_output_dir.mkdir(parents=True, exist_ok=True)
    paths.clean_diagnostics_dir.mkdir(parents=True, exist_ok=True)
    paths.compile_probe_dir.mkdir(parents=True, exist_ok=True)
    paths.validation_json_dir.mkdir(parents=True, exist_ok=True)

    started_at = datetime.now()

    print("\n" + "="*60)
    print(" COMPOSER PIPELINE CONFIGURATION")
    print("="*60)
    print(f"Benchmark ASM input: {paths.benchmark_asm_input_dir}")
    print(f"Input experiment dir: {paths.input_experiment_dir}")
    print(f"Source language: {paths.source_language}")
    print(f"Error JSON: {paths.error_json_path}")
    print(f"Run output dir: {paths.run_output_dir}")
    print(f"Model: {args.model}")
    print(f"Prompt Config: {args.prompt_config}")
    print(f"Max concurrency: {args.max_concurrency}")
    print(f"Max retries: {args.max_retries}")
    print(f"Problems to repair: {len(problems)}")
    print("="*60 + "\n")

    if not problems:
        finished_at = datetime.now()
        final_validation_path, final_validation_error_count = validate_all_fixed_outputs(paths, args)
        write_reports(args, paths, problems, [], started_at, finished_at, final_validation_path, final_validation_error_count)
        print("No errored problems found in input JSON.")
        return 0

    results = asyncio.run(run_async(args, paths, problems, api_key))

    finished_at = datetime.now()
    final_validation_path, final_validation_error_count = validate_all_fixed_outputs(paths, args)
    write_reports(args, paths, problems, results, started_at, finished_at, final_validation_path, final_validation_error_count)

    success_count = sum(1 for result in results if result.succeeded)
    fail_count = len(results) - success_count
    print(f"Composer finished. success={success_count} fail={fail_count}")
    return 0 if fail_count == 0 and final_validation_error_count == 0 else 1

if __name__ == "__main__":
    raise SystemExit(main())